# Generated by Django 5.0.2 on 2024-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API hash'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='api_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='chat_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
