# Generated by Django 5.0.2 on 2024-02-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_telegramaccount_api_hash_telegramaccount_api_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='chat_id',
        ),
    ]
