# Generated by Django 5.0.2 on 2024-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_telegramaccount_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Message ID'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Success'), (2, 'Server Not Received')], default=0),
        ),
    ]
