# Generated by Django 5.0.2 on 2024-02-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_message_msg_id_telegramaccount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='contact',
            name='chat_id',
            field=models.IntegerField(verbose_name='Chat ID of client.'),
        ),
    ]
