# Generated by Django 5.0.2 on 2024-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_contact_is_open_alter_contact_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='chat_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
