# Generated by Django 5.0.2 on 2024-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_telegramaccount_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
